version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/domain_event
      - ./docker/.gitconfig:/root/.gitconfig
      - ./docker/.bashrc:/root/.bashrc
    working_dir: /domain_event
    tty: true
